name: testing
on: [page_build, workflow_dispatch]

jobs:
  grade-learner:
    if: github.event_name == 'page_build'
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
  manual-grade:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: grade pages activity
        id: pages
        uses: githubtraining/check-pages-action@major-refactor
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          
      - name: More info
        if: failure()
        uses: githubtraining/looking-glass-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feedback: ${{ steps.pages.outputs.report }}
